Repository openwisp/openwisp-radius, pull requests merged in 2020-08, with the labels that each got.

#120 [multi-tenancy] Freeradius instance without the organization info
  docs/source/developer/freeradius.rst
  docs/source/user/api.rst
  openwisp_radius/admin.py
  openwisp_radius/api/serializers.py
  openwisp_radius/api/views.py
  openwisp_radius/apps.py
  openwisp_radius/base/models.py
  openwisp_radius/management/commands/upgrade_from_django_freeradius.py
  openwisp_radius/migrations/0014_radiustoken_freeradius_auth.py
  openwisp_radius/migrations/__init__.py
  openwisp_radius/social/views.py
  openwisp_radius/tests/__init__.py
  openwisp_radius/tests/mixins.py
  openwisp_radius/tests/test_admin.py
  openwisp_radius/tests/test_api.py
  openwisp_radius/tests/test_social.py
  openwisp_radius/tests/test_token.py
  tests/openwisp2/sample_radius/migrations/0002_initial_openwisp_app.py
Labels: enhancement

#147 [bug] Honor Postauth password length #116
  openwisp_radius/api/serializers.py
  openwisp_radius/tests/test_api.py
Labels: bug

#150 [bug] unexpected freeradius authorize failed
  openwisp_radius/api/views.py
  openwisp_radius/tests/test_api.py
Labels: bug

#154 [docs] Reordered and improved settings page
  docs/source/index.rst
  docs/source/user/settings.rst
Labels: docs

#155 [fix] Fixed user is already active bug in phone token validation
  openwisp_radius/base/models.py
  openwisp_radius/tests/test_token.py
Labels: bug
